### ISSUE TITLE
skopeo binary is not executable

### ISSUE THREAD

**Issue by klutchell** [warjiang/setup-skopeo#20]
The action downloads the binary into the workspace, but does not set it as executable.

Also, the binary does not appear to be added to the PATH so it must be referenced as `./skopeo` in the workspace.

**Comment by gonmmarques** [comment]
@klutchell  and @andyhan feel free to check this out [v0.3.0](https://github.com/gonmmarques/setup-skopeo/releases/tag/v0.3.0)

You should be able to use it like so:

```yaml
jobs:
  job_id:
    steps:
      - name: 'Set up skopeo'
        uses: gonmmarques/setup-skopeo@v0.3.0
        with:
          version: latest

      - name: 'Test skopeo'
        run: |
          skopeo --version
```
